import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Feed from "../Components/Feed";
import Header from "../Components/Header";
import Sidebar from "../Components/Sidebar";
import Widgets from "../Components/Widgets";
import styles from "../styles/Home.module.css";

export default function Home() {
  //   const router = useRouter();
  //   const { data: session, status } = useSession({
  //     required: true,
  //     onUnauthenticated() {
  //       router.push("/login");
  //     },
  //   });

  // if (status === "authenticated") {
  return (
    <div className="overflow-hidden bg-gray-100 h-screen">
      <Head>
        <title>Facebook-clone</title>
        <meta
          name="google-site-verification"
          content="G7ytNgKJpYbuIlMLvcDW4lq9h1FZC6ez3XPjL2EgwSg"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://links.papareact.com/5me" />
      </Head>

      {/* Header */}
      <Header />

      <main className="flex">
        {/* sidebar */}
        <Sidebar />
        {/* feed */}
        <Feed />
        {/* widgets */}
        <Widgets />
      </main>
    </div>
  );
  // }
}
